blueprint:
  name: 整点报时
  description: 在指定时间段内，使用空调伴侣进行报时提醒
  domain: automation
  source_url: https://github.com/shaonianzhentan/xiaomi_radio
  input:
    tipsType:
      name: 报时方式
      description: "半点报时: /30  整天报时：/0  每小时40分时语音播报: /40"
      selector:
        text:
mode: restart
max_exceeded: silent
trigger:
  - platform: time_pattern
    hours: /1
    minutes: !input tipsType
    seconds: "0"
condition:
  - condition: time
    after: "07:59"
    before: "23:00"
action:
  - service: xiaomi_radio.tts
    data:
      text: >-
        现在的时间是 {%- if now().hour < 12 -%} 上午 {%- elif now().hour == 12 -%} 中午
        {%-     elif now().hour <= 18 -%} 下午 {%- else -%} 晚上 {%- endif %}    
        {{now().strftime("%I:%M")}}
