blueprint:
  name: 整点报时
  description: 在指定时间段内，使用空调伴侣进行报时提醒
  domain: automation
  source_url: https://github.com/shaonianzhentan/xiaomi_radio
  input:
    after_time:
      name: 开始时间
      description: 提示开始时间
      selector:
        time: '07:59'
    before_time:
      name: 结束时间
      description: 提示结束时间
      selector:
        time: '23:00'
mode: restart
max_exceeded: silent
trigger:
  - platform: time_pattern
    hours: /1
    minutes: /30
    seconds: '0'
condition:
  - condition: time
    after: !input after_time
    before: !input before_time
action:
  - service: xiaomi_radio.tts
    data:
      text: >-
        现在的时间是 {%- if now().hour < 12 -%} 上午 {%- elif now().hour == 12 -%} 中午
        {%-     elif now().hour <= 18 -%} 下午 {%- else -%} 晚上 {%- endif %}    
        {{now().strftime("%I:%M")}}